import * as THREE from 'three';
import {Water} from 'three/addons/objects/Water.js';

export const WEATHER_LABELS={clear:'CLEAR SKIES',cloudy:'OVERCAST',fog:'LOW MIST',rain:'PASSING SHOWERS',storm:'THUNDERSTORM',snow:'SNOWFALL'};
export function createClimate({scene,camera,renderer,groundMat,snowMat,snowGround,terrain,pondMesh,waterMat,gardenFlowers,sky,sounds}){
  let mode='auto',current='cloudy',timer=24,lastSeason=-1,cycle=0,flash=0,stormTimer=10,leafAnchor=new THREE.Vector2(Infinity,Infinity);
  const loader=new THREE.TextureLoader();const texture=(name,repeat,color=false)=>{const t=loader.load('./public/textures/'+name+'.jpg');t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(repeat,repeat);t.anisotropy=4;if(color)t.colorSpace=THREE.SRGBColorSpace;return t;};
  const base={map:groundMat.map,normal:groundMat.normalMap,rough:groundMat.roughnessMap};
  const autumn={map:texture('autumn-color',140,true),normal:texture('autumn-normal',140),rough:texture('autumn-rough',140)};
  snowMat.map=texture('snow-color',120,true);snowMat.normalMap=texture('snow-normal',120);snowMat.normalScale.set(.55,.55);snowMat.roughnessMap=texture('snow-rough',120);snowMat.roughness=.94;snowMat.color.set('#e9f0f1');snowMat.transparent=false;snowMat.depthWrite=true;snowGround.position.y=.09;snowMat.needsUpdate=true;
  const mountain=texture('mountain-color',1,true);
  groundMat.onBeforeCompile=shader=>{shader.uniforms.mountainMap={value:mountain};shader.uniforms.snowU={value:0};groundMat.userData.shader=shader;shader.vertexShader='varying vec3 terrainWorld;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <worldpos_vertex>','#include <worldpos_vertex>\n terrainWorld=(modelMatrix*vec4(transformed,1.0)).xyz;');shader.fragmentShader='varying vec3 terrainWorld;uniform sampler2D mountainMap;uniform float snowU;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\n float rockBlend=smoothstep(40.0,70.0,terrainWorld.y);diffuseColor.rgb=mix(diffuseColor.rgb,texture2D(mountainMap,terrainWorld.xz*.15).rgb*.8,rockBlend);diffuseColor.rgb=mix(diffuseColor.rgb,vec3(.92,.95,.98),smoothstep(36.0,60.0,terrainWorld.y)*snowU);');};groundMat.needsUpdate=true;
  // Multi-directional wave normals, shared by the river and the planar pond reflector.
  const nc=document.createElement('canvas');nc.width=nc.height=256;const cx=nc.getContext('2d'),im=cx.createImageData(256,256);for(let y=0;y<256;y++)for(let x=0;x<256;x++){const i=(y*256+x)*4,u=x/256*Math.PI*2,v=y/256*Math.PI*2;im.data[i]=128+Math.sin(u*9+Math.sin(v*3))*30+Math.cos(v*7-u*2)*15;im.data[i+1]=128+Math.cos(v*11+u*3)*26;im.data[i+2]=246;im.data[i+3]=255;}cx.putImageData(im,0,0);const normal=new THREE.CanvasTexture(nc);normal.wrapS=normal.wrapT=THREE.RepeatWrapping;
  waterMat.normalMap=normal;waterMat.normalScale=new THREE.Vector2(.32,.32);waterMat.bumpMap=null;waterMat.color.set('#6d9992');waterMat.roughness=.17;waterMat.metalness=.15;waterMat.envMapIntensity=1.2;waterMat.opacity=.87;waterMat.needsUpdate=true;
  const water=new Water(pondMesh.geometry.clone(),{textureWidth:384,textureHeight:384,waterNormals:normal,alpha:.92,sunDirection:new THREE.Vector3(-.4,.7,.3),sunColor:0xd9e9dd,waterColor:0x294f4b,distortionScale:1.4,fog:true});water.position.copy(pondMesh.position);water.position.y+=.008;scene.add(water);pondMesh.visible=false;
  function iceTexture(){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');
  x.fillStyle='#aecdd8';x.fillRect(0,0,256,256);
  for(let i=0;i<40;i++){x.fillStyle=`rgba(${140+Math.random()*40|0},${180+Math.random()*30|0},${195+Math.random()*25|0},.25)`;x.beginPath();x.arc(Math.random()*256,Math.random()*256,10+Math.random()*30,0,7);x.fill();}
  x.strokeStyle='rgba(255,255,255,.75)';for(let i=0;i<14;i++){x.lineWidth=.8+Math.random();x.beginPath();let px=Math.random()*256,py=Math.random()*256;x.moveTo(px,py);for(let k=0;k<5;k++){px+=(Math.random()-.5)*70;py+=(Math.random()-.5)*70;x.lineTo(px,py);}x.stroke();}
  x.fillStyle='rgba(255,255,255,.5)';for(let i=0;i<120;i++){x.beginPath();x.arc(Math.random()*256,Math.random()*256,.6+Math.random()*1.8,0,7);x.fill();}
  x.fillStyle='rgba(240,246,248,.8)';for(let i=0;i<25;i++){x.beginPath();x.arc(Math.random()*256,Math.random()*256,4+Math.random()*14,0,7);x.fill();}
  const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
  const iceMat=new THREE.MeshStandardMaterial({map:iceTexture(),color:'#d4e6ec',roughness:.38,metalness:.05,transparent:true,opacity:.97});let frozen=false;
  const reflection=water.onBeforeRender;let reflectFrame=0;water.onBeforeRender=function(...args){if(camera.layers.mask!==1)return;if(++reflectFrame%(renderer.getPixelRatio()<1?8:3)===1&&camera.position.distanceTo(water.position)<140)reflection.apply(this,args);};
  const flakeCanvas=document.createElement('canvas');flakeCanvas.width=flakeCanvas.height=32;const fc=flakeCanvas.getContext('2d'),fg=fc.createRadialGradient(16,16,1,16,16,16);fg.addColorStop(0,'#fff');fg.addColorStop(.5,'#ffffffaa');fg.addColorStop(1,'#ffffff00');fc.fillStyle=fg;fc.fillRect(0,0,32,32);
  const flakeData=new Float32Array(1300*3),seeds=Array.from({length:1300},()=>({x:(Math.random()-.5)*58,y:Math.random()*25,z:(Math.random()-.5)*58,s:.7+Math.random()}));const flakeGeo=new THREE.BufferGeometry();flakeGeo.setAttribute('position',new THREE.BufferAttribute(flakeData,3));const snow=new THREE.Points(flakeGeo,new THREE.PointsMaterial({map:new THREE.CanvasTexture(flakeCanvas),color:'#f1f6f4',size:.12,transparent:true,opacity:.8,depthWrite:false}));snow.frustumCulled=false;scene.add(snow);
  const lc=document.createElement('canvas');lc.width=lc.height=128;const l=lc.getContext('2d');l.fillStyle='#b87132';l.beginPath();l.moveTo(64,5);l.bezierCurveTo(119,25,119,100,64,124);l.bezierCurveTo(11,98,4,28,64,5);l.fill();l.strokeStyle='#dbb26d';l.lineWidth=2;l.beginPath();l.moveTo(64,12);l.lineTo(64,118);for(let i=0;i<6;i++){l.moveTo(64,20+i*15);l.lineTo(30,33+i*12);l.moveTo(64,20+i*15);l.lineTo(97,33+i*12);}l.stroke();const leafTex=new THREE.CanvasTexture(lc);leafTex.colorSpace=THREE.SRGBColorSpace;
  const leafMat=new THREE.MeshStandardMaterial({map:leafTex,alphaTest:.5,side:THREE.DoubleSide,color:'#d5ad6c',roughness:1});const falling=new THREE.InstancedMesh(new THREE.PlaneGeometry(.16,.25),leafMat,320),carpet=new THREE.InstancedMesh(new THREE.PlaneGeometry(.15,.23),leafMat,4200);falling.frustumCulled=carpet.frustumCulled=false;scene.add(falling,carpet);const d=new THREE.Object3D();
  {const c=new THREE.Color();const tints=['#ffffff','#ffd9a8','#ffb98a','#e8c890'];for(let j=0;j<320;j++){c.set(tints[j%4]);falling.setColorAt(j,c);}falling.instanceColor.needsUpdate=true;}
  const pc=document.createElement('canvas');pc.width=pc.height=64;const px2=pc.getContext('2d');px2.fillStyle='#f2bcd2';px2.beginPath();px2.ellipse(32,34,20,26,.5,0,7);px2.fill();px2.fillStyle='#f9e2ec';px2.beginPath();px2.ellipse(28,30,11,16,.5,0,7);px2.fill();const petalTex=new THREE.CanvasTexture(pc);petalTex.colorSpace=THREE.SRGBColorSpace;
  const petalMat=new THREE.MeshStandardMaterial({map:petalTex,alphaTest:.4,side:THREE.DoubleSide,roughness:.8,color:'#ffd7e4'});
  const petals=new THREE.InstancedMesh(new THREE.PlaneGeometry(.11,.14),petalMat,220);petals.frustumCulled=false;scene.add(petals);
  let state={kind:current,season:0,precip:0,cloud:.7,fogMultiplier:.7,flash:0,indoors:false};
  function select(next,season){current=next==='snow'&&season!==3?'rain':next==='rain'&&season===3?'snow':next;timer=45+Math.random()*25;}
  function update(dt,now,phase,indoors=false){
    const season=Math.floor(phase)%4;if(season!==lastSeason){lastSeason=season;const maps=season===2?autumn:base;groundMat.map=maps.map;groundMat.normalMap=maps.normal;groundMat.roughnessMap=maps.rough;groundMat.needsUpdate=true;leafAnchor.set(Infinity,Infinity);if(mode==='auto'){select(['rain','clear','fog','snow'][season],season);}else select(mode,season);}
    if(mode==='auto'){timer-=dt;if(timer<=0){const options=[['clear','cloudy','rain','fog'],['clear','cloudy','storm','clear'],['cloudy','fog','rain','clear'],['snow','cloudy','clear','snow']][season];select(options[cycle++%options.length],season);}}
    snowGround.visible=season===3;snowMat.opacity=season===3?1:0;if(groundMat.userData.shader)groundMat.userData.shader.uniforms.snowU.value=season===3?1:0;groundMat.color.set(season===2?'#b4a48a':season===1?'#a4b298':'#a5b29b');
    const precip=['rain','storm','snow'].includes(current)?(current==='storm'?1:.65):0,cloud={clear:.03,cloudy:.75,fog:.6,rain:.9,storm:1,snow:.75}[current];
    if(current==='storm'){stormTimer-=dt;if(stormTimer<=0){flash=.8;stormTimer=9+Math.random()*15;setTimeout(()=>sounds.effect('thunder'),900);}}flash=Math.max(0,flash-dt*2.2);
    state={kind:current,season,precip,cloud,fogMultiplier:{clear:.3,cloudy:.7,fog:2.2,rain:1.1,storm:1.5,snow:1.2}[current],flash,indoors};
    sky.material.uniforms.turbidity.value=current==='clear'?3:14;
    snow.visible=current==='snow'&&!indoors;for(let j=0;j<seeds.length;j++){const r=seeds[j];flakeData.set([camera.position.x+r.x+Math.sin(now*.6+j)*1.5,camera.position.y+((r.y-now*r.s)%25+25)%25-4,camera.position.z+r.z+Math.cos(now*.4+j)],j*3);}flakeGeo.attributes.position.needsUpdate=true;
    falling.visible=carpet.visible=season===2;falling.visible&&=!indoors;
    if(season===2){for(let j=0;j<320;j++){const r=seeds[j];const lx=camera.position.x+r.x,lz=camera.position.z+r.z;const gy=terrain(lx,lz);const cyc=((r.y*2-now*r.s*.85)%14+14)%14;const hgt=.06+cyc*(11.94/14);d.position.set(lx+Math.sin(now*1.4+j*1.7)*(.25+hgt*.22),gy+hgt,lz+Math.cos(now*1.1+j*2.3)*(.2+hgt*.18));d.rotation.set(now*(1+r.s)+j,j*.7+now*.4,Math.sin(now*1.2+j)*1.2);d.scale.setScalar(1);d.updateMatrix();falling.setMatrixAt(j,d.matrix);}falling.instanceMatrix.needsUpdate=true;
      if(leafAnchor.distanceTo(new THREE.Vector2(camera.position.x,camera.position.z))>8){leafAnchor.set(camera.position.x,camera.position.z);for(let j=0;j<4200;j++){const x=camera.position.x+(Math.random()-.5)*80,z=camera.position.z+(Math.random()-.5)*80;d.position.set(x,terrain(x,z)+.025,z);d.rotation.set(-Math.PI/2,0,Math.random()*6.28);d.scale.setScalar(.65+Math.random()*.8);d.updateMatrix();carpet.setMatrixAt(j,d.matrix);}carpet.instanceMatrix.needsUpdate=true;}}
    petals.visible=season===0&&!indoors;if(season===0){for(let j=0;j<220;j++){const r=seeds[(j+640)%1300];const lx=camera.position.x+r.x*.8,lz=camera.position.z+r.z*.8;const gy=terrain(lx,lz);const cyc=((r.y*3-now*r.s*.6)%13+13)%13;const hgt=.05+cyc*(9.95/13);d.position.set(lx+Math.sin(now*1.8+j*2.1)*(.3+hgt*.3),gy+hgt,lz+Math.cos(now*1.5+j)*(.3+hgt*.3));d.rotation.set(now*(1.2+r.s)+j*1.3,j+now*.5,Math.sin(now*2+j)*1.4);d.scale.setScalar(1);d.updateMatrix();petals.setMatrixAt(j,d.matrix);}petals.instanceMatrix.needsUpdate=true;}
    gardenFlowers.forEach((f,j)=>{f.visible=season!==3;const growth=season===0?1.1:season===1?.9:.46;f.scale.setScalar(growth*(1+(f.userData.waterBloom||0)));if(f.userData.petals)f.userData.petals.visible=season<2;f.rotation.z=Math.sin(now*.7+j)*.035;});
    const froze=season===3;if(froze!==frozen){frozen=froze;water.visible=!froze;pondMesh.visible=froze;pondMesh.material=froze?iceMat:waterMat;waterMat.color.set(froze?'#9fc4cf':'#6d9992');waterMat.roughness=froze?.42:.17;}
    water.material.uniforms.time.value=now*.65;water.material.uniforms.distortionScale.value=current==='storm'?2.5:current==='clear'?.7:1.3;water.material.uniforms.waterColor.value.set(season===3?'#617e82':'#294f4b');if(!frozen)normal.offset.set(now*.009,now*.006);
    return state;
  }
  return{update,get state(){return state;},setMode(m,season){mode=m;if(m==='auto'){timer=0;}else select(m,season);},get mode(){return mode;},diagnostics(){return{mode,current,season:lastSeason,snowGround:snowGround.visible,snowfall:snow.visible,autumnLeaves:falling.visible,leafCarpet:carpet.visible,pondReflection:true,ice:frozen,petals:petals.visible,flowersVisible:gardenFlowers.filter(f=>f.visible).length};}};
}
